---
- name: Install curl and wget
  gather_facts: 'yes'
  hosts: webapp1
  become: yes
  remote_user: ec2-user
  

  tasks:
    
    - debug:
        msg: ansible_ssh_user = {{ ansible_ssh_user }}
    
    - name: "run app.sh"
      shell: >
        /bin/bash -c "/tmp/subscript.sh"

    